spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
management:
  security:
    enabled: false
  endpoints:
    web:
      expose: "*"