#
#
#   ---------------------------------------------------------------------
#    HONEYWELL International Inc.
#
#    101 Columbia Road, Morristown
#
#    Morris Plains, New Jersey, United States
#
#   ---------------------------------------------------------------------
#
#    Copyright © 2018 Honeywell International Inc.
#
#    UNPUBLISHED - ALL RIGHTS RESERVED UNDER THE COPYRIGHT LAWS.
#
#    PROPRIETARY AND CONFIDENTIAL INFORMATION.
#
#    DISTRIBUTION, USE AND DISCLOSURE RESTRICTED BY HONEYWELL.
#
#   ---------------------------------------------------------------------
#
#

implementation-class=com.hon.reds.gradle.plugin.REDSDependencyManagementPlugin
